### ISSUE TITLE
create_jobid_folder: 1

### ISSUE THREAD

**Issue by laszewsk** [goerz/LPBS#1]
It would be better to have the initial cfg file to have the value 

create_jobid_folder: 1

otherwise you get 

Traceback (most recent call last):
  File "/Users/.../bin/lqsub", line 500, in <module>
    sys.exit(main())
  File "/.../bin/lqsub", line 496, in main
    return submit_pbs_script(pbs_script, options)
  File "/.../bin/lqsub", line 311, in submit_pbs_script
    retcode = run_pbs_script(pbs_script, job_id, options)
  File "/.../bin/lqsub", line 259, in run_pbs_script
    if os.path.isdir(job_scratch):
UnboundLocalError: local variable 'job_scratch' referenced before assignment

Maybe I need something else, but with the create job folder it seems to work

**Comment by goerz** [comment]
Just a simple undefined variable. No need to change the config. Fixed.
